fixtures:
  repositories:
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    portage: "git://github.com/gentoo/puppet-portage.git"
    provision: 'git://github.com/puppetlabs/provision.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    yumrepo_core: 
      repo: "git://github.com/puppetlabs/puppetlabs-yumrepo_core.git"
      puppet_version: '>= 6.0.0'
  symlinks:
    apache: "#{source_dir}"
    site_apache: "#{source_dir}/spec/fixtures/site_apache"
